export interface Tribe {
  code: string;
  name: string;
  altName?: string;
  region: string;
  population: string;
  description: string;
  culturalNote: string;
  flag: string;
  color: string; // tailwind bg class accent
}

export const TRIBES: Tribe[] = [
  {
    code: "kpe",
    name: "Kpelle",
    altName: "Guerze",
    region: "Bong, Nimba & Lofa Counties",
    population: "~500,000",
    description: "The largest ethnic group in Liberia, the Kpelle people are known for their rich oral tradition, complex social structures, and the Poro and Sande secret societies.",
    culturalNote: "The Kpelle have a rich tradition of storytelling through the use of riddles, proverbs, and folktales passed down through generations.",
    flag: "🌿",
    color: "kola",
  },
  {
    code: "bss",
    name: "Bassa",
    region: "Margibi, Grand Bassa & Rivercess Counties",
    population: "~350,000",
    description: "The Bassa people are one of the largest coastal ethnic groups with a strong maritime heritage and a unique indigenous script.",
    culturalNote: "The Bassa Vah script is one of the few indigenous writing systems developed in West Africa in modern times.",
    flag: "🌊",
    color: "savanna",
  },
  {
    code: "grb",
    name: "Grebo",
    region: "Grand Kru, Maryland & River Gee Counties",
    population: "~200,000",
    description: "The Grebo are known for their warrior traditions and distinctive artistic expressions. They occupy the southeastern coastal region of Liberia.",
    culturalNote: "Grebo oral literature includes elaborate praise songs, elegies, and historical narratives performed at important ceremonies.",
    flag: "🌄",
    color: "earth",
  },
  {
    code: "gio",
    name: "Gio",
    altName: "Dan",
    region: "Nimba County",
    population: "~200,000",
    description: "The Gio (Dan) people are celebrated for their vibrant musical culture, mask-making tradition, and the use of the Dan mask in spiritual ceremonies.",
    culturalNote: "Dan masks are among the most recognized art forms from Liberia, used in initiation ceremonies and community events.",
    flag: "🦅",
    color: "kola",
  },
  {
    code: "mno",
    name: "Mano",
    region: "Nimba County",
    population: "~180,000",
    description: "The Mano people share many cultural practices with their Gio neighbors, including the Poro society, and are known for their agricultural expertise.",
    culturalNote: "The Mano have a strong tradition of iron smelting and blacksmithing, which held high social status in their communities.",
    flag: "⚒️",
    color: "earth",
  },
  {
    code: "kru",
    name: "Kru",
    region: "Sinoe, Grand Kru & Grand Gedeh Counties",
    population: "~200,000",
    description: "The Kru are historically renowned seafarers who were respected across West Africa for their maritime skills and resistance to enslavement.",
    culturalNote: "Kru sailors were sought after by European traders for their exceptional navigational abilities along the West African coast.",
    flag: "⚓",
    color: "savanna",
  },
  {
    code: "lor",
    name: "Lorma",
    altName: "Loma",
    region: "Lofa County",
    population: "~80,000",
    description: "The Lorma people inhabit the forested highlands of Lofa County and are known for their elaborate Poro initiation ceremonies and woodcarving.",
    culturalNote: "Lorma master carvers create some of the most intricate wooden sculptures and masks found in Liberian art.",
    flag: "🌾",
    color: "kola",
  },
  {
    code: "kis",
    name: "Kissi",
    region: "Lofa County",
    population: "~100,000",
    description: "The Kissi people are known for their distinctive penny currency made of iron, and their rich tradition of music using the balafon xylophone.",
    culturalNote: "Kissi Pennies — twisted iron rods used as currency — were once widely traded across the region before colonization.",
    flag: "🎵",
    color: "earth",
  },
  {
    code: "gol",
    name: "Gola",
    region: "Grand Cape Mount & Bomi Counties",
    population: "~100,000",
    description: "The Gola people are known for their powerful Sande and Poro societies, and for producing some of Liberia's most significant carved wooden helmets.",
    culturalNote: "The Sowei helmet mask of the Gola Sande society is one of the most collected and studied art forms from Liberia.",
    flag: "🎭",
    color: "savanna",
  },
  {
    code: "man",
    name: "Mandingo",
    altName: "Mandinka",
    region: "Lofa, Nimba & Bong Counties",
    population: "~150,000",
    description: "The Mandingo are a predominantly Muslim people known for their role as traders, religious scholars, and the keepers of the Quranic tradition in Liberia.",
    culturalNote: "Mandingo griots — called jelis — preserve centuries of oral history through song and storytelling, serving as living libraries of their people.",
    flag: "📿",
    color: "kola",
  },
  {
    code: "mnd",
    name: "Mende",
    region: "Lofa County",
    population: "~60,000",
    description: "The Mende people straddle the border between Liberia and Sierra Leone, sharing a rich cultural heritage including the Sande society and distinctive textile traditions.",
    culturalNote: "Mende women are known for their expertise in weaving intricate country cloth — a woven fabric that holds deep cultural significance.",
    flag: "🏔️",
    color: "earth",
  },
  {
    code: "sap",
    name: "Sapo",
    altName: "Sao",
    region: "Sinoe County",
    population: "~50,000",
    description: "The Sapo people live in the dense rainforest region of southeastern Liberia, near the Sapo National Park named after them, and are skilled forest hunters.",
    culturalNote: "Sapo traditional knowledge of medicinal plants and forest ecology has been passed down through generations of hunters and healers.",
    flag: "🌳",
    color: "savanna",
  },
  {
    code: "bel",
    name: "Belle",
    altName: "Kuwaa",
    region: "Lofa County",
    population: "~15,000",
    description: "One of the smaller ethnic groups in Liberia, the Belle (Kuwaa) people are known for their deep spiritual traditions and close connection to the forest.",
    culturalNote: "The Belle maintain some of the oldest and most secretive initiation rites in Liberia, with ceremonies that can last several months.",
    flag: "🍃",
    color: "kola",
  },
  {
    code: "dey",
    name: "Dey",
    altName: "Dei",
    region: "Montserrado County",
    population: "~20,000",
    description: "The Dey (Dei) are one of the indigenous peoples of the Monrovia area, whose ancestral lands predate the arrival of the Americo-Liberian settlers.",
    culturalNote: "The Dey were among the first groups to interact with American colonists, and their cultural blending with settler culture created unique traditions.",
    flag: "🏙️",
    color: "earth",
  },
  {
    code: "vai",
    name: "Vai",
    region: "Grand Cape Mount County",
    population: "~100,000",
    description: "The Vai people are internationally recognized for independently developing one of the few indigenous African writing systems, the Vai syllabary, in the 19th century.",
    culturalNote: "The Vai syllabary, created around 1833, is one of only a handful of fully functional writing systems ever independently invented in human history.",
    flag: "📜",
    color: "savanna",
  },
  {
    code: "gbd",
    name: "Gbandi",
    region: "Lofa County",
    population: "~80,000",
    description: "The Gbandi people are known for their skilled craftsmanship, particularly in weaving and metalwork, and share close cultural ties with the Lorma and Mende.",
    culturalNote: "Gbandi weavers produce some of Liberia's finest traditional textiles, with patterns that communicate social status and occasion.",
    flag: "🧵",
    color: "kola",
  },
];

export function getTribe(code: string): Tribe | undefined {
  return TRIBES.find(t => t.code === code);
}
